---
- import_tasks: tasks/apt_install.yml
- import_tasks: tasks/ufw_tcp.yml

- import_tasks: mariadb.yml

- name: Copy apache config
  copy: src=000-default.conf
        dest=/etc/apache2/sites-available/
        owner=root
        group=root
        mode=655

- name: Restart apache service
  service: name=apache2 state=restarted
