---
- name: reconfigure tzdata
  command: dpkg-reconfigure -f noninteractive tzdata
  notify: Restart NTP service 

- name: Restart NTP service
  service: name=ntp state=restarted

- name: rebuild locales
  command: /usr/sbin/locale-gen
