# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-09 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate_to_chf', models.DecimalField(decimal_places=5, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True, verbose_name='%Y-%m-%d')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.ExchangeRate_date'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.ExchangeRate_name'),
        ),
    ]
