# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('exchange_rate_to_chf', models.FloatField(max_length=5)),
            ],
        ),
    ]
