# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-27 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
