# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-29 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20171227_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
