# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20171229_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(null=True, verbose_name='%Y-%m-%dT%H:%M:%S'),
        ),
    ]
