# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-29 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_auto_20171229_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(null=True, verbose_name='%Y-%m-%d'),
        ),
    ]
